---
galaxy_info:
  author: Chun Pan Yung
  description: Install all developmental tools.
  license: GPL-2.0-or-later

  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags: []
dependencies:
  - ansi_colle.linux.pnpm
