---
- name: Configure oh-my-post to start on interactive session
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    mode: '0644'
    backup: true
    line: 'eval "$(oh-my-posh init bash --config wholespace)"'
