---
argument_specs:
  main:
    short_description: Main entry point for extra role.
    description: |
      Configure optional settings, including setting up systemd temp directory,
      lazyvim, and bashrc.d directory etc.
    author:
      - Chun Pan Yung
    options: {}
